# Default values for kafka-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

TaskCount: 1

KafkaConnect: "test-connect-kafka-connect"

connector:
  name: "org.apache.camel.kafkaconnector.httpsink.CamelHttpsinkSinkConnector"
  config:
    camel.kamelet.http-sink.method: POST
    camel.kamelet.http-sink.url: https://simplekafkatest.requestcatcher.com/
    errors.tolerance: all
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry:8081
    key.converter.schemas.enable: true
    name: kafka-http-demo-kafka-connector
    output.data.format: JSON
    topics: test1-postgres-instance.public.plant_events
    transforms: tojson
    transforms.tojson.converter.type: value
    transforms.tojson.type: org.apache.camel.kafkaconnector.transforms.SchemaAndStructToJsonTransform
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry:8081
    value.converter.schemas.enable: true
