apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"letsencrypt-staging"},"spec":{"acme":{"email":"iulius.hutuleac@heidelbergmaterials.com","privateKeySecretRef":{"name":"letsencrypt-secret"},"server":"https://acme-staging-v02.api.letsencrypt.org/directory","solvers":[{"http01":{"ingress":{"class":"nginx"}}}]}}}
  creationTimestamp: "2023-09-22T17:46:47Z"
  generation: 1
  name: letsencrypt-staging
  resourceVersion: "6686"
  uid: d4d64e0c-16b0-4b50-aa54-eeadbc43e69e
spec:
  acme:
    email: iulius.hutuleac@heidelbergmaterials.com
    privateKeySecretRef:
      name: letsencrypt-secret
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
status:
  acme:
    lastPrivateKeyHash: gSRiLB/3vc3Gf4eBd6PxUj+BPe6q5FosT7xh32kOO4M=
    lastRegisteredEmail: iulius.hutuleac@heidelbergmaterials.com
    uri: https://acme-staging-v02.api.letsencrypt.org/acme/acct/119403254
  conditions:
  - lastTransitionTime: "2023-09-22T17:46:48Z"
    message: The ACME account was registered with the ACME server
    observedGeneration: 1
    reason: ACMEAccountRegistered
    status: "True"
    type: Ready
