# To use the KafkaConnector resource, you have to first enable the connector operator using
# the strimzi.io/use-connector-resources annotation on the KafkaConnect custom resource.
# From Apache Kafka 3.1.1 and 3.2.0, you also have to add the FileStreamSourceConnector
# connector to the container image. You can do that using the kafka-connect-build.yaml example.
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ include "kafka-connector.fullname" . }}
  labels:
    {{- include "kafka-connector.labels" . | nindent 4 }}
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: {{ .Values.KafkaConnect }}
spec:
  class: {{ .Values.config.connector.class }}
  tasksMax: {{ .Values.TaskCount }}
  config:
    {{- range $key, $value := .Values.connector.config }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
