apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "apicurio-registry.fullname" . }}
  labels:
    enable_postgres_monitoring: "1"
    {{- include "apicurio-registry.labels" . | nindent 4 }}    
spec:
  teamId: "{{ .Release.Name }}"
  enableMasterLoadBalancer: false
  volume:
    size: {{ .Values.Size }}
  numberOfInstances: {{ .Values.Instances }}
  users:
    {{ .Values.Username }}:
      - superuser
      - createdb
  databases:
    {{ .Values.DBName }}: {{ .Values.Username }}
  postgresql:
    version: "{{ .Values.DBVersion }}"
    parameters:
      wal_level: logical
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
      - local     all  all  trust
      - local     replication standby trust
      - host      all  all  0.0.0.0/0   md5
      - host      all  all  ::1/128     md5
      - host      replication standby 0.0.0.0/0 md5
      - hostssl   all all 0.0.0.0/0 md5
      - host      all all 0.0.0.0/0 md5
      - host      replication standby 0.0.0.0/0 md5
      - hostssl   replication standby 0.0.0.0/0 md5
  teamId: hmuser
  users:
    hmuser:
      - superuser
      - createdb
