apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.KafkaUser }}
  labels:
    strimzi.io/cluster: {{ .Values.KafkaCluster }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    # Kafka Connects internal topics used to store configuration, offsets or status
    - resource:
        type: group
        name: {{ .Values.KafkaConnectGroup }}-connect-cluster
      operations:
        - Read
    - resource:
        type: topic
        name: {{ .Values.KafkaConnectGroup }}-connect-cluster-configs
      operations:
        - Create
        - Describe
        - Read
        - Write
    - resource:
        type: topic
        name: {{ .Values.KafkaConnectGroup }}-connect-cluster-status
      operations:
        - Create
        - Describe
        - Read
        - Write
    - resource:
        type: topic
        name: {{ .Values.KafkaConnectGroup }}-connect-cluster-offsets
      operations:
        - Create
        - Describe
        - Read
        - Write
    - resource:
        type: topic
        name: {{ .Values.TopicsPrefix }}
        patternType: prefix
      operations:
        - Create
        - Describe
        - Read
        - Write  
    - resource:
        type: group
        name: {{ .Values.KafkaConnectorPrefix }}
        patternType: prefix
      operations:
        - Create
        - Describe
        - Read
        - Write          


