apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.KafkaUser }}
  labels:
    strimzi.io/cluster: {{ .Values.KafkaCluster }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    {{- range $pkey, $pval := .Values.access }}
      - resource:
          type: topic
          name: {{ index $pval "topicNamePrefix" | quote }}
          patternType: literal
        operation: All
      - resource:
          type: group
          name: connect-cluster
          patternType: literal
        operation: All
      - resource:
          type: topic
          name: connect-cluster-configs
        operations:
          - Create
          - Describe
          - Read
          - Write
      - resource:
          type: topic
          name: connect-cluster-status
        operations:
          - Create
          - Describe
          - Read
          - Write
      - resource:
          type: topic
          name: connect-cluster-offsets
        operations:
          - Create
          - Describe
          - Read
          - Write        
    {{- end }} 

