apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.KafkaUser }}
  labels:
    strimzi.io/cluster: {{ .Values.KafkaCluster }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      {{- range $key, $value := .Values.access }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}

