apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.KafkaUser }}
  labels:
    strimzi.io/cluster: {{ .Values.KafkaCluster }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    {{- range $pkey, $pval := .Values.access }}
    - resource:
        type: topic
        name: {{ index $pval "topicNamePrefix" | quote }}
        patternType: prefix
      operations:
      - Create
      - Describe
      - Write
      host: "*"
    {{- end }} 

