apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.KafkaUser }}
  labels:
    strimzi.io/cluster: {{ .Values.KafkaCluster }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    {{- range $pkey, $pval := .Values.access }}
    # Kafka Connects internal topics used to store configuration, offsets or status
    - resource:
        type: group
        name: connect-cluster
      operations:
        - Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operations:
        - Create
        - Describe
        - Read
        - Write
    - resource:
        type: topic
        name: connect-cluster-status
      operations:
        - Create
        - Describe
        - Read
        - Write
    - resource:
        type: topic
        name: connect-cluster-offsets
      operations:
        - Create
        - Describe
        - Read
        - Write
    # Additional topics and groups used by connectors
    # Change to match the topics used by your connectors
    - resource:
        type: group
        name: connect-cluster
      operations:
       - Read
    - operations:
        - Read
      resource:
        name: connect-kafka-http-demo-kafka-connector
        type: group       
    - resource:
        type: topic
        name: {{ index $pval "topicName" | quote }}
        patternType: prefix
      operations:
        - Create
        - Describe
        - Read
        - Write  
    {{- end }} 

