# Default values for kafka-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kafka:
  enable: true
  name: kafka
  numberOfInstances: 2
  diskSize: 50M
  zookeeperDiskSize: 50M
  config:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    default.replication.factor: 3
    min.insync.replicas: 2
    inter.broker.protocol.version: "3.5"
