apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
data:
  config.yml: |-
    kafka:
      clusters:
        - name: yaml
          bootstrapServers: {{ .Values.BootstrapServers }}
          schemaRegistry: http://schema-registry:8081
          properties:
            security.protocol: SASL_PLAINTEXT
            sasl.mechanism: SCRAM-SHA-512
            sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ .Values.KafkaUsername }}" password="{{ .Values.KafkaPassword }}";
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false